### ISSUE TITLE
an error when run python main.py 1

### ISSUE THREAD

**Issue by kaishijeng** [Oguzhanka/carla-camera-data#2]
I launched carla server with ./CarlaUE4.sh -benchmark -fps=30
Then run python main.py 1 and the following error happens:

ELAPSED TIME: 0.033Traceback (most recent call last):
  File "./main.py", line 67, in <module>
    record.log_actors(server_time)
  File "/opt/carla-simulator/carla-camera-data/recorder.py", line 171, in log_actors
    detected_actors = self.detect_actors(time)
  File "/opt/carla-simulator/carla-camera-data/recorder.py", line 243, in detect_actors
    (255, 0, 0), -1)
TypeError: an integer is required (got type tuple)
Exception ignored in: <function Recorder.__del__ at 0x7f175d3e7d40>
Traceback (most recent call last):
  File "/opt/carla-simulator/carla-camera-data/recorder.py", line 299, in __del__
LookupError: unknown encoding: ascii
WARNING: sensor object went out of the scope but the sensor is still alive in the simulation: Actor 97 (sensor.camera.rgb)
WARNING: sensor object went out of the scope but the sensor is still alive in the simulation: Actor 98 (sensor.camera.semantic_segmentation)
Segmentation fault (core dumped)

Any idea why this happens?
Thanks,

**Comment by Oguzhanka** [comment]
I did not face this issue while I was running the code. However, the following link could be helpful. Maybe this error is related to the opencv version.

https://github.com/opencv/opencv/issues/14866#issuecomment-575288111

**Comment by kaishijeng** [comment]
After I comment out that portion of codes and got another error.
So I will not experiment it anymore

Thanks
